# Generated by Django 5.0.4 on 2024-09-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamalaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='originaal_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
    ]
