# Generated by Django 5.0.4 on 2024-09-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamalaapp', '0002_product_originaal_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='originaal_price',
        ),
    ]
